### ISSUE TITLE
When i start up the bot i get an error "CLIENT_MISSING_INTENTS"

### ISSUE THREAD

**Issue by loky-official** [kabirsingh2004/A-Advance-Discord-Music-Bot-Like-Hydra-#5]
[https://imgur.com/S1xb8ZO](url)

**Comment by Alijkaz** [comment]
I solved this problem myself
Seems the developer didn't update his codes with new discord.js versions and doesn't care about updating readme

You could go ahead and install older versions of discord.js (12.5.3 did the work for me) using:

`npm install discord.js@12.5.3`
